apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/mongodb-secret.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: {{ .Values.api.image }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
