{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  activeDeadlineSeconds: 300
  completions: 1
  template:
    metadata:
      labels:
        job-name: "seed"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: {{ .Values.api.image }}
          command:
            - yarn
            - load
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
{{- end }}