on: [push]
name: okteto-test-action
env:
  EVENT_NUMBER: ${{github.run_id}}
jobs:
  create-socket:
    runs-on: ubuntu-latest
    container:
      image: okteto/okteto:stable
    steps:
      - name: Okteto login
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ secrets.OKTETO_CONTEXT }}

      - name: Create Preview Environment Namespace for Docker socket service
        run: 
          okteto preview deploy dev-previews-test$EVENT_NUMBER --repository https://github.com/jvc5546/test-docker-socket-service.git --branch main

  run-tests:
      needs: create-socket
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Okteto login
          uses: okteto/context@latest
          with:
            token: ${{ secrets.OKTETO_TOKEN }}
            url: ${{ secrets.OKTETO_CONTEXT }}

        - name: Run tests
          uses: okteto/test@latest
          with:
            file: okteto.yml

        - name: Deploy Preview Environment in the same Namespace above
          uses: okteto/deploy-preview@latest
          with:
            file: okteto.yml
            name: dev-previews-test$EVENT_NUMBER

  delete-socket:
    needs: run-tests
    runs-on: ubuntu-latest
    container:
      image: okteto/okteto:stable
    steps:
      - name: Okteto login
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ secrets.OKTETO_CONTEXT }}

      - name: Delete Docker socket service from Preview Environment Namespace
        run: 
          okteto destroy test-docker-socket-service --namespace dev-previews-test$EVENT_NUMBER