on: [push]
name: okteto-test-action
jobs:
  run-tests:
      runs-on: ubuntu-latest
      steps:
  
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Okteto login
          uses: okteto/context@latest
          with:
            token: ${{ secrets.OKTETO_TOKEN }}
            url: ${{ secrets.OKTETO_CONTEXT }}

        - name: Run graphql tests
          uses: okteto/test@latest
          with:
            file: okteto.yml
